name: ereyapressing
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cloud_firestore: ^4.4.0
  firebase_core: ^2.5.0
  
  pinput: ^2.2.7
  flutter:
    sdk: flutter
  firebase_auth: ^4.2.8
  intl_phone_field: ^3.1.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  location: ^4.3.0
  fluttertoast: ^8.0.7
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

android:
  uses-permission: 
    - android.permission.ACCESS_COARSE_LOCATION
    - android.permission.ACCESS_FINE_LOCATION
