// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsgqAgDj1jOdnoLlkmNyDfAoIwbpfLvZs',
    appId: '1:744469859775:web:3f2fc15c25d701cb81e50a',
    messagingSenderId: '744469859775',
    projectId: 'ereyapressing',
    authDomain: 'ereyapressing.firebaseapp.com',
    storageBucket: 'ereyapressing.appspot.com',
    measurementId: 'G-VQTDLZJNLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASyll4MnST5ku87Q9qA-N6AtJNVb7txxw',
    appId: '1:744469859775:android:0057b3e5c08b2ae681e50a',
    messagingSenderId: '744469859775',
    projectId: 'ereyapressing',
    storageBucket: 'ereyapressing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-S77Kd2ckH7J_YcJYoz2k1M9uBoNB6MA',
    appId: '1:744469859775:ios:81c199a7a51eaea581e50a',
    messagingSenderId: '744469859775',
    projectId: 'ereyapressing',
    storageBucket: 'ereyapressing.appspot.com',
    iosClientId: '744469859775-dfbgktad72sqi8c62l7cc073s7vab0ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.ereyapressing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-S77Kd2ckH7J_YcJYoz2k1M9uBoNB6MA',
    appId: '1:744469859775:ios:81c199a7a51eaea581e50a',
    messagingSenderId: '744469859775',
    projectId: 'ereyapressing',
    storageBucket: 'ereyapressing.appspot.com',
    iosClientId: '744469859775-dfbgktad72sqi8c62l7cc073s7vab0ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.ereyapressing',
  );
}
